In [66]:
import sqlalchemy
import pymysql
import importlib
from dotenv import load_dotenv

from sqlalchemy import create_engine, text
import pandas as pd
import os
import yaml
from pathlib import Path
import sys

%load_ext autoreload
%autoreload 2


project_root = Path.cwd().parent
sys.path.append(str(project_root))
import functions as fn
             
#Data raw folder path:
raw_folder = r"C:\Users\ziden\Desktop\Trainings\RNCP-Project\data\raw"
#Data clean folder path:
clean_folder = r"C:\Users\ziden\Desktop\Trainings\RNCP-Project\data\clean"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [67]:
importlib.reload(fn)

In [56]:
#-----------------------------------------------------------------------------
# 1. ESTABLISH SQL CONNECTION AND UPLOAD A TABLE : function name: load_to_sql(file_to_load, sql_table_name)
#-----------------------------------------------------------------------------

#function name: load_to_sql(file_to_load, sql_table_name)

In [72]:
#-----------------------------------------------------------------------------
# 2. LOADING insee_geo_dfs to SQL
#-----------------------------------------------------------------------------
insee_geo_df = fn.insee_geo_flat_extract()

fn.load_to_sql(file_to_load=insee_geo_df, sql_table_name="dim_geo")

File 'insee_geo.csv' is successfully saved to 'data/clean' folder.
Connected to SQL DB: mobile_5g_network_fr
Uploading 34875 rows to 'dim_geo'...
The file was successfully loaded to 'dim_geo' in MySQL.
Opening SQL connection + loading file'dim_geo' took:  6.22sec

In [68]:
#-----------------------------------------------------------------------------
# 3. LOADING sites to SQL
#-----------------------------------------------------------------------------

sites_clean_df = fn.clean_sites_file("file2")

#define the sites table to upload to sql server
columns_to_exclude = ['code_op', 'nom_op', 'nom_reg', 'nom_dep', 'insee_dep','nom_com']
sites_to_sql = sites_clean_df.loc[:, ~sites_clean_df.columns.isin(columns_to_exclude)]

fn.load_to_sql(file_to_load=sites_to_sql, sql_table_name="sites")

File 'insee_sites_clean.csv' is successfully saved to 'data/clean' folder.
Connected to SQL DB: mobile_5g_network_fr
Uploading 118087 rows to 'sites'...
The file was successfully loaded to 'sites' in MySQL.

In [42]:
#-----------------------------------------------------------------------------
# 4. LOADING dim_operator: # dim_operator is directly created in workbench see sql script: "create_dim_operator.sql"
#-----------------------------------------------------------------------------

sites_clean_df = fn.clean_sites_file("file2")
dim_operator = sites_clean_df[["code_op", "nom_op", "operator_id"]].drop_duplicates().sort_values("code_op")

dim_operator

File 'insee_sites_clean.csv' is successfully saved to 'data/clean' folder.

       code_op            nom_op  operator_id
0        20801            Orange            1
31688    20810               SFR            2
89439    20815       Free Mobile            3
60383    20820  Bouygues Telecom            4

In [29]:
#-----------------------------------------------------------------------------
# 5. LOADING dim_protocol: # dim_protocol is directly created in workbench see sql script: "create_dim_protocol.sql"
#-----------------------------------------------------------------------------
clean_qos_df = fn.clean_qos_df("file1")

dim_protocol = clean_qos_df[["protocol_id", "protocole"]].drop_duplicates()
dim_protocol

Number of completeley empty colunms is: 74
Number of irrelevant columns is: 6

number of columns before cleaning:  103

number of columns after cleaning:  23
File '5G_qos_clean.csv' is successfully saved to 'data/clean' folder.

    protocol_id protocole
0             1       WEB
80            2    STREAM
84            3  DOWNLOAD
88            4    UPLOAD

In [77]:
#-----------------------------------------------------------------------------
# 6. LOADING QOS_5G 
#-----------------------------------------------------------------------------

#qos df
clean_qos_df = fn.clean_qos_df("file1")

#define qos table to upload to SQL
qos_to_sql = clean_qos_df.drop(columns = ['protocole', 'operator'])

#Upload qos table
fn.load_to_sql(file_to_load=qos_to_sql, sql_table_name="fact_qos_measurements")

Connected to SQL DB: mobile_5g_network_fr
Uploading 317998 rows to 'fact_qos_measurements'...
The file was successfully loaded to 'fact_qos_measurements' in MySQL.
Opening SQL connection + loading file' fact_qos_measurements' took:  230.58sec