In [22]:
import sqlalchemy
import pymysql
from dotenv import load_dotenv

from sqlalchemy import create_engine, text
import pandas as pd
import os
import yaml
from pathlib import Path
import sys

%load_ext autoreload
%autoreload 2


project_root = Path.cwd().parent
sys.path.append(str(project_root))
import functions as fn
             
#Data raw folder path:
raw_folder = r"C:\Users\ziden\Desktop\Trainings\RNCP-Project\data\raw"
#Data clean folder path:
clean_folder = r"C:\Users\ziden\Desktop\Trainings\RNCP-Project\data\clean"

In [19]:
#-----------------------------------------------------------------------------
# 1. ESTABLISHING CONNECTION TO MYSQL DB FROM PYTHON
#-----------------------------------------------------------------------------

load_dotenv()

# Retrieve credentials
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db = os.getenv("DB_NAME")

connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}"

engine = create_engine(connection_string)

with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))
    print(result.scalar())

mobile_5g_network_fr

In [24]:
#-----------------------------------------------------------------------------
# 2. LOADING insee_geo_df → dim_geo
#-----------------------------------------------------------------------------

insee_geo_df = fn.insee_geo_flat_extract()
insee_geo_df.to_sql(
    name="dim_geo",
    con=engine,
    if_exists="append",
    index=False
)


print(insee_geo_df.shape)
print(insee_geo_df.columns.tolist())

File 'insee_geo.csv' is successfully saved to 'data/clean' folder.
(34875, 6)
['insee_com', 'com_name', 'insee_dep', 'dep_name', 'insee_reg', 'reg_name']

In [26]:
#-----------------------------------------------------------------------------
# 2. LOADING dim_operator: # dim_operator is directly created in workbench see sql script: "create_dim_operator.sql"
#-----------------------------------------------------------------------------

sites_clean_df = fn.clean_sites_file("file2")
dim_operator = sites_clean_df[["code_op", "nom_op"]].drop_duplicates().sort_values("code_op")

File 'insee_sites_clean.csv' is successfully saved to 'data/clean' folder.

       code_op            nom_op
0        20801            Orange
31688    20810               SFR
89439    20815       Free Mobile
60383    20820  Bouygues Telecom

In [29]:
#-----------------------------------------------------------------------------
# 3. LOADING dim_protocol: # dim_protocol is directly created in workbench see sql script: "create_dim_protocol.sql"
#-----------------------------------------------------------------------------
clean_qos_df = fn.clean_qos_df("file1")

dim_protocol = clean_qos_df[["protocol_id", "protocole"]].drop_duplicates()
dim_protocol

Number of completeley empty colunms is: 74
Number of irrelevant columns is: 6

number of columns before cleaning:  103

number of columns after cleaning:  23
File '5G_qos_clean.csv' is successfully saved to 'data/clean' folder.

    protocol_id protocole
0             1       WEB
80            2    STREAM
84            3  DOWNLOAD
88            4    UPLOAD

In [27]:
clean_qos_df = fn.clean_qos_df("file1")
clean_qos_df.operator.unique()

Number of completeley empty colunms is: 74
Number of irrelevant columns is: 6

number of columns before cleaning:  103

number of columns after cleaning:  23
File '5G_qos_clean.csv' is successfully saved to 'data/clean' folder.

<StringArray>
['SFR', 'Bouygues', 'Orange', 'Free']
Length: 4, dtype: str